routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/usuario', 'CadastroController@index');
Route::post('/usuario', 'CadastroController@store');
Route::resource('usuario', 'CadastroController');
Route::get('/pesquisa_restaurantes', 'CadastroController@show');

app/Entregador.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entregador extends Model
{
    protected $fillable = ['nome','cpf'];
    protected $guarded = ['id','created_at','updated_at'];
    protected $table = 'usuario_entregador';
}

app/Motorista.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Motorista extends Model
{
    protected $fillable = ['nome','cpf','cnh','placa','modelo','cor'];
    protected $guarded = ['id','created_at','updated_at'];
    protected $table = 'usuario_motorista';
}

app/Passageiro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Passageiro extends Model
{
    protected $fillable = ['nome','cpf','endereco','id_pagamento','id_origem'];
    protected $guarded = ['id','created_at','updated_at'];
    protected $table = 'usuario_passageiro';
}

app/Restaurante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Restaurante extends Model
{
    protected $fillable = ['nome','cpf','cnpj','razao_social','endereco'];
    protected $guarded = ['id','created_at','updated_at'];
    protected $table = 'usuario_restaurante';
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Usuario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    protected $fillable = ['nome','cpf'];
    protected $guarded = ['id','created_at','updated_at'];
    protected $table = 'usuarios';
}

app/Http/Controllers/CadastroController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Usuario;
use App\Entregador;
use App\Motorista;
use App\Passageiro;
use App\Restaurante;

class CadastroController extends Controller
{
    public function index()
    {
       // $usuario = Usuario::orderBy('cpf', 'desc')->paginate(10);
       // return view('usuario.index',['usuario' => $usuario]);
        return view('usuario.index');
    }
  
    public function create()
    {
        return view('usuario.create');
    }
  
    public function store(Request $request)
    {
       
        $usuario = new Usuario([
        'nome' => $request->get('nome'),
        'cpf'=> $request->get('cpf')]);
        $usuario->save();

        if($request->get('tipo_usuario') == 1){
            $entregador = new Entregador([
            'nome' => $request->get('nome'),
            'cpf'=> $request->get('cpf')]);
            $entregador->save();
        } else if($request->get('tipo_usuario') == 2){
            $motorista = new Motorista([
            'nome' => $request->get('nome'),
            'cpf'=> $request->get('cpf'),
            'cnh' => $request->get('cnh')]);
            $motorista->save();
        }else if($request->get('tipo_usuario') == 3){
            $passageiro = new Passageiro([
            'nome' => $request->get('nome'),
            'cpf'=> $request->get('cpf')]);
            $passageiro->save();
        }else if($request->get('tipo_usuario') == 4){
            $restaurante = new Restaurante([
            'nome' => $request->get('nome'),
            'cpf'=> $request->get('cpf')]);
            $restaurante->save();
        }

         return redirect('/usuario')->with('success', 'User has been added');
        
       
    }
  
    public function show()
    {
        
        $restaurante = Restaurante::orderBy('cpf', 'desc')->paginate(10);
            return view('usuario.show',['restaurante' => $restaurante]);
    }
  
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('products.edit',compact('product'));
    }
  
    public function update(ProductRequest $request, $id)
    {
        $product = Product::findOrFail($id);
        $product->name        = $request->name;
        $product->description = $request->description;
        $product->quantity    = $request->quantity;
        $product->price       = $request->price;
        $product->save();
        return redirect()->route('products.index')->with('message', 'Product updated successfully!');
    }
  
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        return redirect()->route('products.index')->with('alert-success','Product hasbeen deleted!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cadastro.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Cadastro</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <div class="container">
	<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" id="nome" placeholder="Nome completo">
  </div>
  <div class="form-group">
    <label for="cpf">CPF</label>
    <input type="text" class="form-control" id="cpf" placeholder="000.000.000-00">
  </div>
  <div class="container">
    <h5>Tipo usuário</h5>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
      <label class="form-check-label" for="inlineRadio1">Passageiro</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
      <label class="form-check-label" for="inlineRadio2">Motorista</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
      <label class="form-check-label" for="inlineRadio2">Entregador</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
      <label class="form-check-label" for="inlineRadio2">Restaurante</label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

resources/views/usuario/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Cadastro</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <style>
     .container {
         width: 100vw;
         height: 100vh;
         display: flex;
         flex-direction: row;
         justify-content: center;
         align-items: center
     }
     .box {
         width: 300px;
         height: 300px;
         background: #fff;
     }
     
     body {
        margin: 0px;
 }
 </style>
</head>
<body>
  <div class="container">
	<form action="{{ route('usuario.store') }}" method="POST">
    @csrf
  <!--<div class="form-row">
    <div class="form-group col-md-6">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" placeholder="Password">
    </div>
  </div>-->
  <div class="box">
    <h5 style="text-align: center;">Cadastro</h5>
  <div class="form-row">
    <div class="form-group col-md-6">

      <label for="nome">Nome</label>
      <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome completo">
    </div>
    <div class="form-group col-md-6">
      <label for="cpf">CPF</label>
      <input type="text" class="form-control" id="cpf" name="cpf" placeholder="000.000.000-00">
    </div>
  </div>
 
  <div>
    <h5>Tipo usuário</h5>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="tipo_usuario" id="inlineRadio1" value="1">
      <label class="form-check-label" for="inlineRadio1">Entregador</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="tipo_usuario" id="inlineRadio2" value="2">
      <label class="form-check-label" for="inlineRadio2">Motorista</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="tipo_usuario" id="inlineRadio2" value="3">
      <label class="form-check-label" for="inlineRadio2">Passageiro</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="tipo_usuario" id="inlineRadio2" value="4">
      <label class="form-check-label" for="inlineRadio2">Restaurante</label>
    </div>
  </div>

  <button type="submit" class="btn btn-primary" style="margin-left: 105px; margin-top: 15px" >Cadastrar</button>
  </div>
</form>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

resources/views/usuario/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Cadastro</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <style>
     .container {
         width: 100vw;
         height: 100vh;
         display: flex;
         flex-direction: row;
         justify-content: center;
         align-items: center
     }
     .box {
         width: 300px;
         height: 300px;
         background: #fff;
     }
     
     body {
        margin: 0px;
 }
 </style>
</head>
<body>
  <div class="container">
   <form>
    @csrf
    <div class="form-row">
      <div class="form-group col-md-4">
        <div class="box">
          <h5>Restaurantes Parceiros</h5>
          <table class="table">    
            <thead class="thead-light">
              <tr>    
                <th scope="col">Restaurantes</th>
                <th scope="col">Endereço</th>
              </tr>
            </thead>
            <tbody>
             @foreach ($restaurante as $r) <tr>

              <td>{{ $r->nome }}</td>
              <td>{{ $r->endereco }}</td>
              </tr> @endforeach
              
            </tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</form>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>